version: '1.0'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile_backend
    network_mode: host
    environment:
      - TOKEN=${TOKEN}
      - NODE_APP_API_ENDPOINT=${URL}
      - JENKINS_USERNAME=${JENKINS_USERNAME}
    volumes:
      - ./resume-backend/src:/app/src
      - ./resume-backend/public:/app/public

  react:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./self-building-resume/src:/app/src
      - ./self-building-resume/public:/app/public
    environment:
      - REACT_APP_API_ENDPOINT=${URL}

  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - '8080:8080'
    volumes:
      - jenkins:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"

  nginx:
    image: nginx
    network_mode: 'host'
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf

volumes:
  jenkins:
